Quickpi - blocklyQuickpiLib - Added translation for two blockly functions
France-ioi/bebras-modules pull request #45
Opened 2020-09-18 13:55 UTC by NicolasWent

I have translated two blockly functions in french + added the x0, y0 needed for them.

I need this pull request to do screenshots for the documentation, can you tell me if you disagree with anything please?

2020-09-18 14:25 UTC, mblockelet requested changes

2020-09-18 14:25 UTC, mblockelet commented on pemFioi/quickpi/blocklyQuickPi_lib.js
> +            isPointSet: "le pixel est-il affiché sur l'écran x₀: %1 y₀: %2",
Je mettrais quelque chose de plus court, par exemple "pixel affiché en x_0: y_0:", il vaut mieux éviter les blocs trop longs.

2020-09-21 07:33 UTC, NicolasWent commented on pemFioi/quickpi/blocklyQuickPi_lib.js
> +            isPointSet: "le pixel est-il affiché sur l'écran x₀: %1 y₀: %2",
J'ai changé en "pixel affiché en..."

2020-09-21 08:16 UTC, smadbe approved these changes

2020-09-21 08:57 UTC, mblockelet approved these changes

2020-09-21 08:58 UTC, merged