QuickPi - Changed category 'Action' to 'Actuators' which is more relevant
France-ioi/bebras-modules pull request #46
Opened 2020-09-21 09:47 UTC by NicolasWent

The blockly category "action" has been renamed to "actuator", which is a more relevant name for these components.

I needed to add the "actuator" category for all languages, but since now, actuator only exist in QuickPi, so only QuickPi is normally impacted by these changes.

For the translations, the file and line to modify for translation is referenced inside of the Google Sheet.

2020-09-21 16:03 UTC, mblockelet requested changes
Apart from that line which shouldn't have been modified, everything is good for me.

2020-09-21 16:03 UTC, mblockelet commented on pemFioi/quickAlgo/i18n.js
> +         actions: "Action",
When you commit, check that you didn't accidentally modify lines you didn't intend to.

2020-09-22 07:39 UTC, NicolasWent commented on pemFioi/quickAlgo/i18n.js
> +         actions: "Action",
Ok, didn't saw that thank you.

The line has been modified in the last commit.

2020-09-22 10:16 UTC, mblockelet approved these changes

2020-09-22 12:03 UTC, smadbe approved these changes
For such a simple word, I think it would worth translating it in German, Spanish, ... using google translate. (to prevent missing translation later)

2020-09-22 13:10 UTC, smadbe approved these changes
great

2020-09-22 16:39 UTC, mblockelet approved these changes

2020-09-22 16:39 UTC, merged