Add function resetDisplay to redraw grid when Raphael paper is destroyed and recreated
France-ioi/bebras-modules pull request #86
Opened 2021-08-19 15:48 UTC by SebastienTainon

@mblockelet Surprisingly, there wasn't any `resetDisplay` function in this version of the robot library. I've created one.
The purpose of this function is to destroy any previous display and recreate it without changing any internal state of the robot.
Could you confirm it's ok to do this? Or do you think I need to create a new version for this?

2021-09-29 09:22 UTC, mblockelet requested changes
Code is fine, I would just rename the functions to avoid confusion.

2021-09-29 09:22 UTC, mblockelet commented on pemFioi/blocklyRobot_lib-1.0.0.js
> +   context.resetDisplay = function() {
`resetDisplay` is meant to be called during a `context.reset`, and works like this in some other libraries. (Note that the code split between `reset` and `resetDisplay` is not completely properly implemented in all libraries, but will need to be when multiple libraries are used at the same time.)

I would hence name it `redrawDisplay` instead, as this doesn't do a "reset" of the items.

2021-09-29 09:22 UTC, mblockelet commented on pemFioi/blocklyRobot_lib-1.0.0.js
> +   context.getCurrentState = function() {
I would name it `getInnerState` or `getContextState`, and rename `reloadState` to `reloadInnerState` or `reloadContextState`, to make the code clearer (as `reloadState `is the name of a Bebras API point, which spans calls up to `quickAlgo/subtask.js`, and naming it the same would be confusing).

2021-09-29 14:13 UTC, SebastienTainon commented
Thanks for the input, that's renamed :wink:

2021-10-11 13:26 UTC, mblockelet approved these changes
:+1:

2021-10-11 13:30 UTC, merged